### ISSUE TITLE
LTS version

### ISSUE THREAD

**Issue by hypery2k** [Shimmi/docker-jenkins#2]
Do you plan a LTS version?

**Comment by Shimmi** [comment]
@hypery2k Hi, I will add it! Give me a while :)

**Comment by hypery2k** [comment]
Thanks ;)

**Comment by Shimmi** [comment]
@hypery2k Just pushed update that adds a new tag `lts`. Just give it a while, please. It needs to be built. You can see the progress here: https://hub.docker.com/r/shimmi/jenkins/builds/
